# Generated by Django 3.1 on 2020-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbl', models.CharField(default='não classificada', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='lbl',
        ),
    ]
