# Generated by Django 3.1 on 2020-08-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0002_auto_20200813_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='image',
            name='lbl',
            field=models.CharField(default='não classificada', max_length=200),
        ),
    ]
