# Generated by Django 3.1 on 2020-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0004_auto_20200813_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagem',
            field=models.ImageField(default='media/img.jpg', upload_to='media/'),
        ),
    ]
