# Generated by Django 3.1 on 2020-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0007_auto_20200814_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lbl', models.CharField(default='não classificada', max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imagem',
            field=models.ImageField(db_column='img', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lbl',
            field=models.CharField(default='não classificada', max_length=20),
        ),
    ]
