# Generated by Django 3.1 on 2020-08-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0008_auto_20200815_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifier',
            new_name='Result',
        ),
    ]
