# Generated by Django 3.1 on 2020-08-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0009_auto_20200815_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='image',
            name='prob',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
