# Generated by Django 3.1 on 2020-08-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_ou_cachorro', '0010_auto_20200817_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prob',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
